<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
        <p class="float-xs-right hidden-sm-up">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div class="jumbotron">
            <h1>Champinho's APK acreanus!</h1>
            <p>Download APKs encefalus acreanus binotopicos champoso alves</p>
        </div>
        <div class="row apk-list">
            <?php foreach ($this->apps as $app) : ?>
                <div class="apk-detail" style="">
                    <div class="apk-image">
                        <img src="<?php echo $app->getUrl(); ?>"/>
                    </div>
                    <div class="apk-description">
                        <p><?php echo $app->getName(); ?></p>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star"></span>
                        <span class="fa fa-star-half-o"></span>
                        <span class="fa fa-star-o"></span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
        </div>
    </div><!--/span-->
</div><!--/row-->
