<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">
        <p class="float-xs-right hidden-sm-up">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="offcanvas">Toggle nav</button>
        </p>
        <div class="jumbotron">
            <h1>Hello, world!</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some
                responsive-range viewport sizes to see it in action.</p>
        </div>
        <div class="row">
            <?php for ($i = 0; $i <= 12; $i++) : ?>
                <div class="col-xs-3">
                    <h5>Heading</h5>
                    <p class="small">Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus
                        commodo, tortor mauris condimentum nibh. </p>
                    <p><a class="btn btn-secondary btn-xs" href="#" role="button">Ver &raquo;</a></p>
            </div>
            <?php endfor; ?>
        </div>
    </div>

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
        </div>
    </div><!--/span-->
</div><!--/row-->
